name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      #working-directory: ./AFexcuses
      run: docker build . --file Dockerfile --tag afexcuses:$(date +%s)
